name: Build and Deploy Jekyll site

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build with jekyll
        uses: actions/jekyll-build-pages@v1

      # pnpm
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
          version: 10.2.0
      - name: build 2025
        working-directory: ./2025
        run: |
          pnpm install --frozen-lockfile
          pnpm build
      - name: copy 2025 to _site
        shell: bash
        run: |
          mkdir -p _site/2025
          cp -r ./2025/dist/ ./_site/2025/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs:
      - build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    if: github.ref == 'refs/heads/gh-pages'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
