name: lint

on:
  push:
  pull_request:

jobs:
  lint-2025:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2025
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
          version: 10.4.0
      - run: pnpm install --frozen-lockfile
      - run: pnpm check
      - run: pnpm lint
